print("in order to execute addition please enter 2 integers")
print("enter the  first value")
integer1 = input()
integer1 = int(integer1)
print("now enter the second value")
integer2 = input()
integer2 = int(integer2)
summation = integer1 + integer2
summation = str(summation)
print("the result is "  + summation + " .")
